on:

  push:
    branches:
      - main
  workflow_dispatch:
name: 🎉Deploy to FTP
runs-on: ubuntu-latest
steps:
  - name: Get latest code
    uses: actions/checkout@v2.3.2

  - name: Sync File
    uses: SamKirkland/FTP-Deploy-Action@4.0.0
    with:
      server: ftp.maulana.one
      username: ${{ secrets.FTP_USERNAME }}
      password: ${{ secrets.FTP_PASSWORD }}
      server-dir: /